### PR TITLE
Added the gmp files to this branch.

### PR DESCRIPTION
**Pull request by mgriebling**
I've added the gmp files to this branch.  You may have other files you're using so please substitute those instead.

### CODE REVIEW

**Comment by mgriebling** [comment]
Generally it seems to be a fairly nice general-purpose calculator.  I'm not convinced anyone can really use a million digits or even more than a hundred but it does set you apart from others 😉.  My ideal calculator looks more like this (based on the original Magic Number Machine):

Screenshot 2023-03-17 at 5 48 14 AM

The main features I'm interested in would be:

1. Graphical display of equations as they are typed.  Magic Number Machine does this the best of any calculators I've seen but unfortunately the code is still in Objective-C.
2. Paper tape display to keep track of previous results.  These can be copied into the main display screen.
3. Fairly large precision maybe 100 digits max.  User selectable.
4. Scrollable display so the user can scroll in all 100 digits or a really long equation.
5. Conversions would be a nice feature, especially monetary rates conversions (hard to find a decent free site for these though).
6. Speaking the keys and the result.  I've got this working on the Mac already.
7. Imaginary number support.  I've got this on the Mac too in several variants.
8. Set of constants whose symbols appear on-screen.  (Already have this).
9. Plotting capabilities (only 2D for now).
10. Magic Number Machine also had array/matrix functions which I don't necessarily need.
11. Fractional separators (user-enabled).  Good for really long numbers.
12. Logical functions.

Magic Number Machine already has many of these features but, unfortunately is not iOS-friendly.

**Comment by joachimneumann** [comment]
Hi, 

Thanks for your pull request. I agree, that it makes sense to add the gmp and mpfr files to the respository.
I also looked at your improvements to the build.sh script and they make sense. Thanks for these improvements!

I am new to git pull requests and I might handle them incorrectly. That I have done is fetching your pull request into a new local branch, modifying this a little bit (see below) and then committing and pushing the changes, and then merging into the Mac branch. Would you suggest a different way?

I am not sure how to handle the change in the DEVELOPMENT_TEAM in the file project.pbxproj and the signing identity. Both are different for each developer. Maybe they could be pulled from a file that is not in the repository, I am not sure how to do that best. For how, I have reverted these two IDs.

The two files libgmp.a and libmpfr.a in the folders x86_64-catalyst arm64-catalyst are not used to build the iPhone or Mac, app. The Xcode project uses the unchanged libraries in gmp.xcframework and mpfr.xcframework. Shouldn't we also update these frameworks with the new libraries?

**Comment by joachimneumann** [comment]
With respect to your ideas related to the Magic Number Machine, this would definitively be a much more powerful and useful calculator. I might also collaborate with you on that.

From a product perspective, I would suggest to separate the two calculators. My original idea was to create a calculator that looks and feels very close to the Apple iPhone and Mac calculators, with the added high precision. 
I of course agree that a precision of more than one hundred digits not not useful in real life applications. Astronomers  sometimes need more digits than what ordinary calculators provide, but 100 digits (as you propose) is more than sufficient for them. Millions of digits is a nerdy project, admitted.

I would imagine to branch off a the development of the more powerful calculator. This would be done as new views and additional product targets - all in the same repository. Alternatively, we might want to fork the repository. I am not sure what is better.

Let me know what you think - Greetings Joachim

**Comment by mgriebling** [comment]
> With respect to your ideas related to the Magic Number Machine, this would definitively be a much more powerful and useful calculator. I might also collaborate with you on that.
> 
> From a product perspective, I would suggest to separate the two calculators. My original idea was to create a calculator that looks and feels very close to the Apple iPhone and Mac calculators, with the added high precision. I of course agree that a precision of more than one hundred digits not not useful in real life applications. Astronomers sometimes need more digits than what ordinary calculators provide, but 100 digits (as you propose) is more than sufficient for them. Millions of digits is a nerdy project, admitted.
> 
> I would imagine to branch off a the development of the more powerful calculator. This would be done as new views and additional product targets - all in the same repository. Alternatively, we might want to fork the repository. I am not sure what is better.
> 

It would be great to merge the two calculators.  Best approach maybe the algorithms from gmp and Magic
Number Machine (MNM) in a Swift Package and GUI written in SwiftUI.  
I have essentially the full GUI (in storyboard form unfortunately) for the Mac but nothing for hand-held devices.
I also have the Mac GUI in SwiftUI but haven't tried merging with the code from the MNM.
It is probably easier to strip out features than to add them in order to come up with a basic calculator.  
The problem with the Magic Number Machine is that the code is mainly in objective-c and would be difficult to maintain.  
I have started to translate the numerical algorithms, which can do radix arithmetic, and have the basic code done.
While I like the approach of using the gmp math library, I believe it only performs calculations using base 2 arithmetic.
Almost all handheld calculators use base 10 or decimal arithmetic.  I've experimented with several decimal number
libraries and was intending to use one on my calculator.  Problem: not all scientific functions exist.  Perhaps a
hybrid approach might be possible where we use the gmp math functions (like gamma - proven accuracy) and 
use n-radix or decimal math in the calculator operations for which decimal functions exist.  With approximate
scientific functions like gamma and sine, base 10 calculations are not necessary.  We can convert the gmp
numbers to whatever format we might use in the new calculator.

Not sure how well versed you are in radix arithmetic but numbers like `0.1` cannot be exactly represented (ever)
in a base 2 arithmetic scheme.  So gmp must be rounding their numbers before displaying them.  Advantages of
base 10 or decimal math is that these numbers are always exact and don't need rounding.  Multiplying 0.1 x 0.1
gives exactly 0.01.  Since humans are used to decimal math it makes sense for the calculator.  BTW, if you check
out the `0.1` representation in Double precision it ends up being `0.10000000000000001`.

The MNM uses a multi-radix system with fixed maximum digits (currently set to 50 in base 10) so it can do calculations 
in any base. The binary bases are useful for logical functions and base 10 is usually used for calculations.  
MNM already has many of the basic scientific functions built in so just special functions like erf and gamma 
are needed from gmp.

My main focus right now is on getting the MNM tree-building and numeric algorithms into a Swift Package — either
with the original objective-c or swift translation.  We can then use the library wherever we like.  We can put a
SwiftUI front-end on top of this and produce either a basic calculator or more advanced version.  It would also
be possible to put SwiftUI code in a Storyboard but don't think that's the best route forward.  To get this moving,
I'll try to put the Object-C code into a Swift Package first.  Unfortunately, the expression tree-building code is tightly tied
to the GUI so this may not be easy.  I'll let you know of my progress.

It would be great if you could do a gmp version that works natively on Mac OS.  BTW, I'd prefer to run the calculator
natively on the Mac and not through Mac Catalyst or Designed for iPad.  I'm still using an Intel-based Mac but
have access to an M1 Arm-based Mac.

Cheers, Mike

**Comment by mgriebling** [comment]
> With respect to your ideas related to the Magic Number Machine, this would definitively be a much more powerful and useful calculator. I might also collaborate with you on that.

Sounds good.

> From a product perspective, I would suggest to separate the two calculators. My original idea was to create a calculator that looks and feels very close to the Apple iPhone and Mac calculators, with the added high precision. I of course agree that a precision of more than one hundred digits not not useful in real life applications. Astronomers sometimes need more digits than what ordinary calculators provide, but 100 digits (as you propose) is more than sufficient for them. Millions of digits is a nerdy project, admitted.

That was actually my original thought as well.  It would be especially useful to have a Mac-like calculator on the iPad.
BTW, I love the square keys on the Mac calculator and think this would work well in the iPad as well.  Do you prefer
the "chicklet" keys?  Maybe a user preference?  Really like your color scheme in place of the orange keys BTW. 

Cheers, Mike

**Comment by mgriebling** [comment]
> I am not sure how to handle the change in the DEVELOPMENT_TEAM in the file project.pbxproj and the signing identity. Both are different for each developer. Maybe they could be pulled from a file that is not in the repository, I am not sure how to do that best. For how, I have reverted these two IDs.

This has always been a problem and don't really have a solution.  Your suggestion is what we did on another project.
The .pbxprog file was excluded from git and we locally had a file copy.

> The two files libgmp.a and libmpfr.a in the folders x86_64-catalyst arm64-catalyst are not used to build the iPhone or Mac, app. The Xcode project uses the unchanged libraries in gmp.xcframework and mpfr.xcframework. Shouldn't we also update these frameworks with the new libraries?

Yes, and I would like a native mac version as well.  No idea how to build these frameworks so maybe you take the lead on this.

BTW, maybe we can move this discussion to WhatsApp or something.

Best wishes, Mike

**Pull request merged**
